src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtudiantRepository::class)]
class Etudiant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50)]
    private $name;

    #[ORM\Column(type: 'string', length: 50)]
    private $Prenom;

    #[ORM\ManyToOne(targetEntity: Section::class)]
    private $section;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getSection(): ?Section
    {
        return $this->section;
    }

    public function setSection(?Section $section): self
    {
        $this->section = $section;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $designation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function __toString(): string
    {
        return $this->designation;
    }


}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('Prenom')
            ->add('section')
            ->add('editer',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Entity\Personne;
use App\Form\EtudiantType;
use App\Form\PersonneType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etudiant')]
class EtudiantController extends AbstractController
{
    #[Route('/', name: 'etudiant.list')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repo = $doctrine->getRepository(Etudiant::class);
        $etudiants = $repo->findAll();

        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiants,
        ]);
    }

    #[Route('/edit/{id?0}', name: 'etudiant.edit')]
    public function editEtudiant(Etudiant $etudiant=null,ManagerRegistry $doctrine,Request $request)
    {
        if (!$etudiant){
            $etudiant = new Etudiant();
        }
        $form=$this->createForm(EtudiantType::class);
        $form->handleRequest($request);
        if($form->isSubmitted()){

            $manager=$doctrine->getManager();
            $manager->persist($etudiant);
            $manager->flush();

            $this->addFlash('success','etudiant added successfully');

            return $this->redirectToRoute('etudiant.list');

        }else{

            return $this->render('personne/addEtudiant.html.twig', [
                'form' => $form->createView()
            ]);
        }




    }
}

src/Controller/TestController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    #[Route('/test', name: 'app_test')]
    public function index(): Response
    {
        return $this->render('test/index.html.twig', [
            'controller_name' => 'TestController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link rel="stylesheet" href="{{ asset('node_modules/bootstrap/dist/css/bootstrap.css') }}">


    </head>
    <body>
    {% for message in app.session.flashBag.get('success') %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.session.flashBag.get('erreur') %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.session.flashBag.get('info') %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
    {% endfor %}


        {% block body %}{% endblock %}
    </body>
</html>

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des etudiants{% endblock %}

{% block body %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Prenom</th>
            <th scope="col">Nom</th>
            <th scope="col">section</th>
            <th scope="col">action</th>
        </tr>
        </thead>

        <tbody>
        {% for etudiant in etudiants %}
        <tr>
            <th scope="row">{{ etudiant.prenom }}</th>
            <td>{{ etudiant.name }}</td>
            <td>{{ etudiant.section }}</td>
            <td>
                <a href="{{path('etudiant.edit',{id:etudiant.id})}}" class="card-link">Edit</a>
                <a href="{{path('etudiant.edit',{id:etudiant.id})}}" class="card-link">delete</a>
            </td>
        </tr>
        {% endfor %}


        </tbody>
    </table>
{% endblock %}

templates/personne/addEtudiant.html.twig
{% extends 'base.html.twig' %}



{% block body %}
   <div class="container">
       {{ form(form) }}
   </div>

{% endblock %}

{% block title %}
    Personne Form
{% endblock %}